#define BASE			3
#define SHOULDER		5
#define ELBOW			6
#define WRISTX			9
#define WRISTY			10
#define GRIPPER			11
#define SERVO_MIN		0
#define SERVO_MAX		180
#define GRIPPER_MIN		70
#define GRIPPER_MAX		120
